use_frameworks!

target 'Split_Example' do
    
  pod 'Split', :path => '../'

  target 'Split_Tests' do
  
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'Mockingjay'
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end

  end
end
