included: # paths to include during linting. `--path` is ignored if present.
  - Split
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Split/Common/Yaml
  - Split/Network/NetworkReachabilityManager.swift
  - Split/Engine/Hashing/Murmur3Hash.swift

# Align with Google Swift Guidelines and SwiftFormat configuration
disabled_rules:
  - trailing_whitespace # Sometimes needed for markdown and multi-line string literals

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Customized rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
    - x
    - y
    - i
    - j
    - k
    - n
    - db

type_name:
  min_length: 3
  max_length: 50

function_parameter_count:
  warning: 6
  error: 8

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

trailing_comma:
  mandatory_comma: true

force_cast: warning
force_try: warning

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown)