#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef SPLIT_SWIFT_H
#define SPLIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Dispatch;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Split",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC5Split11BaseMatcher")
@interface BaseMatcher : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC5Split14AllKeysMatcher")
@interface AllKeysMatcher : BaseMatcher
@end

@class NSString;
@class NSEntityDescription;
@class NSManagedObjectContext;
SWIFT_CLASS_NAMED("AttributeEntity")
@interface AttributeEntity : NSManagedObject
@property (nonatomic, copy) NSString * _Nullable attributes;
@property (nonatomic) int64_t updatedAt;
@property (nonatomic, copy) NSString * _Nullable userKey;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5Split20BaseInSegmentMatcher")
@interface BaseInSegmentMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split14BetweenMatcher")
@interface BetweenMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split18BetweenMatcherData")
@interface BetweenMatcherData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface BetweenMatcherData (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

SWIFT_CLASS("_TtC5Split20BetweenSemverMatcher")
@interface BetweenSemverMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split24BetweenStringMatcherData")
@interface BetweenStringMatcherData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CertificatePinningConfigBuilder;
/// Configuration class for Certificate Pinning.
SWIFT_CLASS("_TtC5Split24CertificatePinningConfig")
@interface CertificatePinningConfig : NSObject
/// Provides a builder for CertificatePinningConfig.
+ (CertificatePinningConfigBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Builder class for constructing a CertificatePinningConfig.
SWIFT_CLASS_NAMED("Builder")
@interface CertificatePinningConfigBuilder : NSObject
/// Builds and returns a CertificatePinningConfig with the added pins.
///
/// throws:
/// CertificatePinningError if any pin cannot be parsed.
///
/// returns:
/// A configured CertificatePinningConfig instance.
- (CertificatePinningConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Adds a certificate pin for the specified host.
/// The certificate file must be in DER format.
/// \param host The host for which to add the pin.
///
/// \param certificateName The name of the certificate file (without the <code>.der</code> extension) located in the app bundle.
/// The method will automatically look for a <code>.der</code> file with this name in the main bundle.
/// Ensure the certificate file is correctly included in your app’s bundle resources.
///
///
/// returns:
/// The Builder instance for chaining.
- (CertificatePinningConfigBuilder * _Nonnull)addPinForHost:(NSString * _Nonnull)host certificateName:(NSString * _Nonnull)certificateName;
/// Adds a key hash pin for the specified host.
/// \param host The host for which to add the pin.
///
/// \param keyHash A string representing the base64-encoded key hash along with its hashing algorithm.
/// The format must follow the pattern <code>"algorithm/hash"</code>, where:
/// - <code>algorithm</code> is the name of the hashing algorithm used (e.g., <code>sha256</code>, <code>sha1</code>).
/// - <code>hash</code> is the base64-encoded hash value generated by applying the specified algorithm to the key.
/// \code
///      Example Format:
///      - `"sha256/g8gd29aGVsbybEP="`
///
///      Detailed Example:
///      - If you have a key hash generated using the SHA-256 algorithm, it should look something like:
///        `"sha256/aGVsbG8gd29ybGQ="`, where `"aGVsbG8gd29ybGQ="` is the base64-encoded result of the hash.
///
/// \endcode
///
/// returns:
/// The Builder instance for chaining.
- (CertificatePinningConfigBuilder * _Nonnull)addPinForHost:(NSString * _Nonnull)host hash:(NSString * _Nonnull)keyHash;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Custom error type for certificate pinning errors, conforming to LocalizedError.
SWIFT_CLASS("_TtC5Split23CertificatePinningError")
@interface CertificatePinningError : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC5Split9Condition")
@interface Condition : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface Condition (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

SWIFT_CLASS("_TtC5Split23ContainsAllOfSetMatcher")
@interface ContainsAllOfSetMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split23ContainsAnyOfSetMatcher")
@interface ContainsAnyOfSetMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split21ContainsStringMatcher")
@interface ContainsStringMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split8DateTime")
@interface DateTime : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5Split35DefaultFallbackTreatmentsCalculator")
@interface DefaultFallbackTreatmentsCalculator : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC5Split25DefaultHttpRequestManager")
@interface DefaultHttpRequestManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURLSession;
@class NSURLSessionDataTask;
@class NSURLResponse;
@class NSData;
@interface DefaultHttpRequestManager (SWIFT_EXTENSION(Split)) <NSURLSessionDataDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveResponse:(NSURLResponse * _Nonnull)response completionHandler:(void (^ _Nonnull)(NSURLSessionResponseDisposition))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveData:(NSData * _Nonnull)data;
@end

@class NSURLSessionTask;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;
@interface DefaultHttpRequestManager (SWIFT_EXTENSION(Split)) <NSURLSessionTaskDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
@end

@class SplitResult;
@class EvaluationOptions;
enum SplitEvent : NSInteger;
SWIFT_PROTOCOL("_TtP5Split11SplitClient_")
@protocol SplitClient
- (NSString * _Nonnull)getTreatment:(NSString * _Nonnull)split attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTreatment:(NSString * _Nonnull)split SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsForSplits:(NSArray<NSString *> * _Nonnull)splits attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (SplitResult * _Nonnull)getTreatmentWithConfig:(NSString * _Nonnull)split SWIFT_WARN_UNUSED_RESULT;
- (SplitResult * _Nonnull)getTreatmentWithConfig:(NSString * _Nonnull)split attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigForSplits:(NSArray<NSString *> * _Nonnull)splits attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTreatment:(NSString * _Nonnull)split attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsForSplits:(NSArray<NSString *> * _Nonnull)splits attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (SplitResult * _Nonnull)getTreatmentWithConfig:(NSString * _Nonnull)split attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigForSplits:(NSArray<NSString *> * _Nonnull)splits attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (void)onEvent:(enum SplitEvent)event execute:(void (^ _Nonnull)(void))action;
- (void)onEvent:(enum SplitEvent)event runInBackground:(BOOL)runInBackground execute:(void (^ _Nonnull)(void))action;
- (void)onEvent:(enum SplitEvent)event queue:(dispatch_queue_t _Nonnull)queue execute:(void (^ _Nonnull)(void))action;
- (BOOL)trackWithTrafficType:(NSString * _Nonnull)trafficType eventType:(NSString * _Nonnull)eventType SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithTrafficType:(NSString * _Nonnull)trafficType eventType:(NSString * _Nonnull)eventType value:(double)value SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithEventType:(NSString * _Nonnull)eventType SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithEventType:(NSString * _Nonnull)eventType value:(double)value SWIFT_WARN_UNUSED_RESULT;
/// Creates or updates the value for the given attribute
- (BOOL)setAttributeWithName:(NSString * _Nonnull)name value:(id _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
/// Retrieves the value of a given attribute so it can be checked by the customer if needed
- (id _Nullable)getAttributeWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
/// It will create or update all the given attributes
- (BOOL)setAttributes:(NSDictionary<NSString *, id> * _Nonnull)values SWIFT_WARN_UNUSED_RESULT;
/// Retrieve the full attributes map
- (NSDictionary<NSString *, id> * _Nullable)getAttributes SWIFT_WARN_UNUSED_RESULT;
/// Removes a given attribute from the map
- (BOOL)removeAttributeWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
/// Clears all attributes stored in the SDK.
- (BOOL)clearAttributes SWIFT_WARN_UNUSED_RESULT;
- (void)flush;
- (void)destroy;
- (void)destroyWithCompletion:(void (^ _Nullable)(void))completion;
- (BOOL)trackWithTrafficType:(NSString * _Nonnull)trafficType eventType:(NSString * _Nonnull)eventType properties:(NSDictionary<NSString *, id> * _Nullable)properties SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithTrafficType:(NSString * _Nonnull)trafficType eventType:(NSString * _Nonnull)eventType value:(double)value properties:(NSDictionary<NSString *, id> * _Nullable)properties SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithEventType:(NSString * _Nonnull)eventType properties:(NSDictionary<NSString *, id> * _Nullable)properties SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithEventType:(NSString * _Nonnull)eventType value:(double)value properties:(NSDictionary<NSString *, id> * _Nullable)properties SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsByFlagSet:(NSString * _Nonnull)flagSet attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsByFlagSets:(NSArray<NSString *> * _Nonnull)flagSets attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigByFlagSet:(NSString * _Nonnull)flagSet attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigByFlagSets:(NSArray<NSString *> * _Nonnull)flagSets attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsByFlagSet:(NSString * _Nonnull)flagSet attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsByFlagSets:(NSArray<NSString *> * _Nonnull)flagSets attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigByFlagSet:(NSString * _Nonnull)flagSet attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigByFlagSets:(NSArray<NSString *> * _Nonnull)flagSets attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC5Split18DefaultSplitClient")
@interface DefaultSplitClient : NSObject <SplitClient>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface DefaultSplitClient (SWIFT_EXTENSION(Split))
- (void)flush;
- (void)destroy;
- (void)destroyWithCompletion:(void (^ _Nullable)(void))completion;
@end

@interface DefaultSplitClient (SWIFT_EXTENSION(Split))
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsByFlagSet:(NSString * _Nonnull)flagSet attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsByFlagSets:(NSArray<NSString *> * _Nonnull)flagSets attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigByFlagSet:(NSString * _Nonnull)flagSet attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigByFlagSets:(NSArray<NSString *> * _Nonnull)flagSets attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
@end

@interface DefaultSplitClient (SWIFT_EXTENSION(Split))
- (void)onEvent:(enum SplitEvent)event execute:(void (^ _Nonnull)(void))action;
- (void)onEvent:(enum SplitEvent)event runInBackground:(BOOL)runInBackground execute:(void (^ _Nonnull)(void))action;
- (void)onEvent:(enum SplitEvent)event queue:(dispatch_queue_t _Nonnull)queue execute:(void (^ _Nonnull)(void))action;
@end

@interface DefaultSplitClient (SWIFT_EXTENSION(Split))
- (SplitResult * _Nonnull)getTreatmentWithConfig:(NSString * _Nonnull)split SWIFT_WARN_UNUSED_RESULT;
- (SplitResult * _Nonnull)getTreatmentWithConfig:(NSString * _Nonnull)split attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTreatment:(NSString * _Nonnull)split SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTreatment:(NSString * _Nonnull)split attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsForSplits:(NSArray<NSString *> * _Nonnull)splits attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigForSplits:(NSArray<NSString *> * _Nonnull)splits attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
@end

@interface DefaultSplitClient (SWIFT_EXTENSION(Split))
- (NSString * _Nonnull)getTreatment:(NSString * _Nonnull)split attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsForSplits:(NSArray<NSString *> * _Nonnull)splits attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (SplitResult * _Nonnull)getTreatmentWithConfig:(NSString * _Nonnull)split attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigForSplits:(NSArray<NSString *> * _Nonnull)splits attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsByFlagSet:(NSString * _Nonnull)flagSet attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsByFlagSets:(NSArray<NSString *> * _Nonnull)flagSets attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigByFlagSet:(NSString * _Nonnull)flagSet attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigByFlagSets:(NSArray<NSString *> * _Nonnull)flagSets attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
@end

@interface DefaultSplitClient (SWIFT_EXTENSION(Split))
- (BOOL)trackWithTrafficType:(NSString * _Nonnull)trafficType eventType:(NSString * _Nonnull)eventType SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithTrafficType:(NSString * _Nonnull)trafficType eventType:(NSString * _Nonnull)eventType value:(double)value SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithEventType:(NSString * _Nonnull)eventType SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithEventType:(NSString * _Nonnull)eventType value:(double)value SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithTrafficType:(NSString * _Nonnull)trafficType eventType:(NSString * _Nonnull)eventType properties:(NSDictionary<NSString *, id> * _Nullable)properties SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithTrafficType:(NSString * _Nonnull)trafficType eventType:(NSString * _Nonnull)eventType value:(double)value properties:(NSDictionary<NSString *, id> * _Nullable)properties SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithEventType:(NSString * _Nonnull)eventType properties:(NSDictionary<NSString *, id> * _Nullable)properties SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithEventType:(NSString * _Nonnull)eventType value:(double)value properties:(NSDictionary<NSString *, id> * _Nullable)properties SWIFT_WARN_UNUSED_RESULT;
@end

@interface DefaultSplitClient (SWIFT_EXTENSION(Split))
- (BOOL)setAttributeWithName:(NSString * _Nonnull)name value:(id _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)getAttributeWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setAttributes:(NSDictionary<NSString *, id> * _Nonnull)values SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nullable)getAttributes SWIFT_WARN_UNUSED_RESULT;
- (BOOL)removeAttributeWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (BOOL)clearAttributes SWIFT_WARN_UNUSED_RESULT;
@end

@class Key;
@protocol SplitManager;
enum UserConsent : NSInteger;
/// This protocol was renamed from SplitFactoryProtocol to SplitFactory
/// to follow Swift guidelines
/// Also all methods where replaced by read only variables following Uniform Access Principle
SWIFT_PROTOCOL("_TtP5Split12SplitFactory_")
@protocol SplitFactory
/// Default Split client instance. This would be the first client created on factory init
///
/// returns:
/// An instance of a class implementing SplitClient protocol
@property (nonatomic, readonly, strong) id <SplitClient> _Nonnull client;
/// Allows getting a new client instance for other Key using the current created factory
/// \param key The corresponding Key object for this new SplitClient
///
///
/// returns:
/// An instance of a class implementing SplitClient protocol
- (id <SplitClient> _Nonnull)clientWithKey:(Key * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
/// Allows getting a new client instance for other Key using the current created factory
/// \param matchingKey A matching key to create a Key object for this new SplitClient
///
///
/// returns:
/// An instance of a class implementing SplitClient protocol
- (id <SplitClient> _Nonnull)clientWithMatchingKey:(NSString * _Nonnull)matchingKey SWIFT_WARN_UNUSED_RESULT;
/// Allows getting a new client instance for other Key using the current created factory
/// \param matchingKey The matching key to create a Key object for this new SplitClient
///
/// \param bucketingKey The bucketing key to create a Key object for this new SplitClient
///
///
/// returns:
/// An instance of a class implementing SplitClient protocol
- (id <SplitClient> _Nonnull)clientWithMatchingKey:(NSString * _Nonnull)matchingKey bucketingKey:(NSString * _Nullable)bucketingKey SWIFT_WARN_UNUSED_RESULT;
/// Current Split manager instance
///
/// returns:
/// The current instance of a class implementing SplitManager protocol
@property (nonatomic, readonly, strong) id <SplitManager> _Nonnull manager;
/// Enables/Disables User Consents data storing
/// If enabled impressions and events are going to be tracked and sent to backend
- (void)setUserConsentWithEnabled:(BOOL)enabled;
@property (nonatomic, readonly) enum UserConsent userConsent;
/// Current Split SDK Version
///
/// returns:
/// A String representation of the current SDK version
@property (nonatomic, readonly, copy) NSString * _Nonnull version;
@end

/// Default implementation of SplitManager protocol
SWIFT_CLASS("_TtC5Split19DefaultSplitFactory")
@interface DefaultSplitFactory : NSObject <SplitFactory>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) enum UserConsent userConsent;
@property (nonatomic, readonly, strong) id <SplitClient> _Nonnull client;
@property (nonatomic, readonly, strong) id <SplitManager> _Nonnull manager;
@property (nonatomic, readonly, copy) NSString * _Nonnull version;
- (id <SplitClient> _Nonnull)clientWithKey:(Key * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (id <SplitClient> _Nonnull)clientWithMatchingKey:(NSString * _Nonnull)matchingKey SWIFT_WARN_UNUSED_RESULT;
- (id <SplitClient> _Nonnull)clientWithMatchingKey:(NSString * _Nonnull)matchingKey bucketingKey:(NSString * _Nullable)bucketingKey SWIFT_WARN_UNUSED_RESULT;
- (void)setUserConsentWithEnabled:(BOOL)enabled;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SplitClientConfig;
/// Protocol describing the necessary components to build
/// a SplitFactory concrete implementation
SWIFT_PROTOCOL("_TtP5Split19SplitFactoryBuilder_")
@protocol SplitFactoryBuilder
/// Sets the client API Key
/// returns: the current instance of SplitFactoryBuilder implementation
- (id <SplitFactoryBuilder> _Nonnull)setApiKey:(NSString * _Nonnull)apiKey;
/// Sets the Matching Key to use. This method is specially usefull when creating
/// a Key without Bucketing Key. If no Matching Key or Key is set the build method
/// will fail.
/// \param matchingKey A string representing matching key
///
///
/// returns:
/// the current instance of SplitFactoryBuilder implementation
- (id <SplitFactoryBuilder> _Nonnull)setMatchingKey:(NSString * _Nonnull)matchingKey;
/// Sets the Bucketing Key to use. This method could be used in conjunction with setMatchingKey
/// to avoid creating explicitly a Key instance
/// \param bucketingKey A string representing bucketing key
///
///
/// returns:
/// the current instance of SplitFactoryBuilder implementation
- (id <SplitFactoryBuilder> _Nonnull)setBucketingKey:(NSString * _Nonnull)bucketingKey;
/// Sets the Key to use. This method could be used instead of setMatchingKey
/// and setBucketing
/// \param key An instances of Key class
///
///
/// returns:
/// the current instance of SplitFactoryBuilder implementation
- (id <SplitFactoryBuilder> _Nonnull)setKey:(Key * _Nonnull)key;
/// Sets the Split configuration to use. If this method is avoided
/// default configuration values will be used
/// \param config An instances of SplitConfig class
///
///
/// returns:
/// the current instance of SplitFactoryBuilder implementation
- (id <SplitFactoryBuilder> _Nonnull)setConfig:(SplitClientConfig * _Nonnull)config;
/// Builds the SplitFactory implementation instance based on set values
///
/// returns:
/// An instance of SplitFactory protocol implementation
- (id <SplitFactory> _Nullable)build SWIFT_WARN_UNUSED_RESULT;
@end

/// Default implementation of factory builder.
/// This class is intended to use as a kind of Director in the future. It will use
/// another concrete class implementing the same protocol to build the factory.
/// The idea is to avoid some boilerplate code when creating the factory.
/// For now it’s just the defaul factory.
SWIFT_CLASS("_TtC5Split26DefaultSplitFactoryBuilder")
@interface DefaultSplitFactoryBuilder : NSObject <SplitFactoryBuilder>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (id <SplitFactoryBuilder> _Nonnull)setApiKey:(NSString * _Nonnull)apiKey;
- (id <SplitFactoryBuilder> _Nonnull)setMatchingKey:(NSString * _Nonnull)matchingKey;
- (id <SplitFactoryBuilder> _Nonnull)setBucketingKey:(NSString * _Nonnull)bucketingKey;
- (id <SplitFactoryBuilder> _Nonnull)setKey:(Key * _Nonnull)key;
- (id <SplitFactoryBuilder> _Nonnull)setConfig:(SplitClientConfig * _Nonnull)config;
- (id <SplitFactory> _Nullable)build SWIFT_WARN_UNUSED_RESULT;
@end

@class SplitView;
SWIFT_PROTOCOL("_TtP5Split12SplitManager_")
@protocol SplitManager
@property (nonatomic, readonly, copy) NSArray<SplitView *> * _Nonnull splits;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull splitNames;
- (SplitView * _Nullable)splitWithFeatureName:(NSString * _Nonnull)featureName SWIFT_WARN_UNUSED_RESULT;
@end

/// Default implementation of SplitManager protocol
SWIFT_CLASS("_TtC5Split19DefaultSplitManager")
@interface DefaultSplitManager : NSObject <SplitManager>
@property (nonatomic, readonly, copy) NSArray<SplitView *> * _Nonnull splits;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull splitNames;
- (SplitView * _Nullable)splitWithFeatureName:(NSString * _Nonnull)featureName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC5Split17DependencyMatcher")
@interface DependencyMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split21DependencyMatcherData")
@interface DependencyMatcherData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface DependencyMatcherData (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

SWIFT_CLASS("_TtC5Split15EndsWithMatcher")
@interface EndsWithMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split21EqualToBooleanMatcher")
@interface EqualToBooleanMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split14EqualToMatcher")
@interface EqualToMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split20EqualToSemverMatcher")
@interface EqualToSemverMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split17EqualToSetMatcher")
@interface EqualToSetMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split17EvaluationOptions")
@interface EvaluationOptions : NSObject
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable properties;
- (nonnull instancetype)initWithProperties:(NSDictionary<NSString *, id> * _Nullable)properties OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("EventEntity")
@interface EventEntity : NSManagedObject
@property (nonatomic, copy) NSString * _Nonnull storageId;
@property (nonatomic, copy) NSString * _Nonnull body;
@property (nonatomic) int64_t createdAt;
@property (nonatomic) NSInteger sizeInBytes;
@property (nonatomic) int32_t status;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5Split8Excluded")
@interface Excluded : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5Split15ExcludedSegment")
@interface ExcludedSegment : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5Split17FallbackSanitizer")
@interface FallbackSanitizer : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// A class that represents a fallback treatment configuration for feature flags.
/// This class is used to define fallback treatments that will be used at
/// factory level or flag level.
SWIFT_CLASS("_TtC5Split17FallbackTreatment")
@interface FallbackTreatment : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull treatment;
@property (nonatomic, readonly, copy) NSString * _Nullable config;
@property (nonatomic, readonly, copy) NSString * _Nullable label;
/// Initializes a new FallbackTreatment instance.
/// \param treatment The treatment String to use as fallback.
///
/// \param config Optional dynamic configuration String for the treatment.
///
- (nonnull instancetype)initWithTreatment:(NSString * _Nonnull)treatment config:(NSString * _Nullable)config OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class Builder;
SWIFT_CLASS("_TtC5Split24FallbackTreatmentsConfig")
@interface FallbackTreatmentsConfig : NSObject
@property (nonatomic, readonly, strong) FallbackTreatment * _Nullable global;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, FallbackTreatment *> * _Nonnull byFlag;
+ (Builder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC5Split24FallbackTreatmentsConfig7Builder")
@interface Builder : NSObject
- (FallbackTreatmentsConfig * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (Builder * _Nonnull)global:(FallbackTreatment * _Nonnull)treatment SWIFT_WARN_UNUSED_RESULT;
- (Builder * _Nonnull)byFlag:(NSDictionary<NSString *, FallbackTreatment *> * _Nonnull)byFlagFallbacks SWIFT_WARN_UNUSED_RESULT;
- (Builder * _Nonnull)globalWithString:(NSString * _Nonnull)treatment SWIFT_WARN_UNUSED_RESULT;
- (Builder * _Nonnull)byFlagWithString:(NSDictionary<NSString *, NSString *> * _Nonnull)byFlagFallbacks SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("GeneralInfoEntity")
@interface GeneralInfoEntity : NSManagedObject
@property (nonatomic) int64_t longValue;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nullable stringValue;
@property (nonatomic) int64_t updatedAt;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5Split27GreaterThanOrEqualToMatcher")
@interface GreaterThanOrEqualToMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split33GreaterThanOrEqualToSemverMatcher")
@interface GreaterThanOrEqualToSemverMatcher : BaseMatcher
@end

SWIFT_CLASS_NAMED("HashedImpressionEntity")
@interface HashedImpressionEntity : NSManagedObject
@property (nonatomic) uint32_t impressionHash;
@property (nonatomic) int64_t time;
@property (nonatomic) int64_t createdAt;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;
SWIFT_CLASS("_TtC5Split10Impression")
@interface Impression : NSObject
@property (nonatomic, copy) NSString * _Nullable feature;
@property (nonatomic, copy) NSString * _Nullable keyName;
@property (nonatomic, copy) NSString * _Nullable treatment;
@property (nonatomic, readonly, strong) NSNumber * _Nullable timestamp;
@property (nonatomic, readonly, strong) NSNumber * _Nullable changeNum;
@property (nonatomic, copy) NSString * _Nullable label;
@property (nonatomic, copy) NSString * _Nullable bucketingKey;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable attributes;
@property (nonatomic, copy) NSString * _Nullable properties;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("ImpressionEntity")
@interface ImpressionEntity : NSManagedObject
@property (nonatomic, copy) NSString * _Nonnull storageId;
@property (nonatomic, copy) NSString * _Nonnull body;
@property (nonatomic) int64_t createdAt;
@property (nonatomic) int32_t status;
@property (nonatomic, copy) NSString * _Nonnull testName;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("ImpressionsCountEntity")
@interface ImpressionsCountEntity : NSManagedObject
@property (nonatomic, copy) NSString * _Nonnull storageId;
@property (nonatomic, copy) NSString * _Nonnull body;
@property (nonatomic) int64_t createdAt;
@property (nonatomic) int32_t status;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5Split21InLargeSegmentMatcher")
@interface InLargeSegmentMatcher : BaseInSegmentMatcher
@end

SWIFT_CLASS("_TtC5Split19InListSemverMatcher")
@interface InListSemverMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split25InRuleBasedSegmentMatcher")
@interface InRuleBasedSegmentMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split16InSegmentMatcher")
@interface InSegmentMatcher : BaseInSegmentMatcher
@end

SWIFT_CLASS("_TtC5Split3Key")
@interface Key : NSObject
- (nonnull instancetype)initWithMatchingKey:(NSString * _Nonnull)matchingKey bucketingKey:(NSString * _Nullable)bucketingKey OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC5Split11KeySelector")
@interface KeySelector : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface KeySelector (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

SWIFT_CLASS("_TtC5Split24LessThanOrEqualToMatcher")
@interface LessThanOrEqualToMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split30LessThanOrEqualToSemverMatcher")
@interface LessThanOrEqualToSemverMatcher : BaseMatcher
@end

/// Split Client protocol implementation for Locahost mode.<br/>
/// This mode is intended to use for development purposes.
/// This implementation loads a local file called localhost.splits<br/>
/// which has the following line format: SPLIT TREATMENT.<br/>
/// Also you can include comments to the file starting a line with the # character
/// <ul>
///   <li>
///     Example: A simple <code>localhost.splits</code> file<br/>
///     <code># This line is a comment</code><br/>
///     <code># Following line has split = FEATURE_ONE and treatment = ON</code><br/>
///     <code>FEATURE_ONE ON</code><br/>
///     <code>FEATURE_TWO OFF</code><br/>
///     <code># Previous line has split = FEATURE_TWO, treatment = OFF</code>
///   </li>
/// </ul>
/// If a file called <em>localhost.splits</em> is included into the project bundle,
/// it will be used as initial file. It will be copied to the cache folder, then
/// it can be edited while app is running to simulate split changes.
/// When no <code>localhost.splits</code> is added to the app bundle, an empty file will be
/// created in cache folder.
/// Enabled debug mode, the <em>localhost.splits</em> file location will be logged
/// to the console so that is possible to open it with a text editor when working
/// on the simulator.
/// When using the device to run the app, the file can be modified by
/// overwritting the app’s bundle from the <em>Device and Simulators</em> tool.
/// For more information
/// <ul>
///   <li>
///     see also:
///     <a href="https://docs.split.io/docs/ios-sdk-overview#section-localhost">Split iOS SDK</a>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC5Split20LocalhostSplitClient")
@interface LocalhostSplitClient : NSObject <SplitClient>
- (NSString * _Nonnull)getTreatment:(NSString * _Nonnull)split attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTreatment:(NSString * _Nonnull)split SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTreatment:(NSString * _Nonnull)split attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsForSplits:(NSArray<NSString *> * _Nonnull)splits attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsForSplits:(NSArray<NSString *> * _Nonnull)splits attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (SplitResult * _Nonnull)getTreatmentWithConfig:(NSString * _Nonnull)split SWIFT_WARN_UNUSED_RESULT;
- (SplitResult * _Nonnull)getTreatmentWithConfig:(NSString * _Nonnull)split attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (SplitResult * _Nonnull)getTreatmentWithConfig:(NSString * _Nonnull)split attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigForSplits:(NSArray<NSString *> * _Nonnull)splits attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigForSplits:(NSArray<NSString *> * _Nonnull)splits attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (void)onEvent:(enum SplitEvent)event runInBackground:(BOOL)runInBackground execute:(void (^ _Nonnull)(void))action;
- (void)onEvent:(enum SplitEvent)event queue:(dispatch_queue_t _Nonnull)queue execute:(void (^ _Nonnull)(void))action;
- (void)onEvent:(enum SplitEvent)event execute:(void (^ _Nonnull)(void))action;
- (BOOL)trackWithTrafficType:(NSString * _Nonnull)trafficType eventType:(NSString * _Nonnull)eventType SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithTrafficType:(NSString * _Nonnull)trafficType eventType:(NSString * _Nonnull)eventType value:(double)value SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithEventType:(NSString * _Nonnull)eventType SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithEventType:(NSString * _Nonnull)eventType value:(double)value SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithTrafficType:(NSString * _Nonnull)trafficType eventType:(NSString * _Nonnull)eventType properties:(NSDictionary<NSString *, id> * _Nullable)properties SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithTrafficType:(NSString * _Nonnull)trafficType eventType:(NSString * _Nonnull)eventType value:(double)value properties:(NSDictionary<NSString *, id> * _Nullable)properties SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithEventType:(NSString * _Nonnull)eventType properties:(NSDictionary<NSString *, id> * _Nullable)properties SWIFT_WARN_UNUSED_RESULT;
- (BOOL)trackWithEventType:(NSString * _Nonnull)eventType value:(double)value properties:(NSDictionary<NSString *, id> * _Nullable)properties SWIFT_WARN_UNUSED_RESULT;
- (void)flush;
- (void)destroy;
- (void)destroyWithCompletion:(void (^ _Nullable)(void))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface LocalhostSplitClient (SWIFT_EXTENSION(Split))
- (BOOL)setAttributeWithName:(NSString * _Nonnull)name value:(id _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)getAttributeWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setAttributes:(NSDictionary<NSString *, id> * _Nonnull)values SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nullable)getAttributes SWIFT_WARN_UNUSED_RESULT;
- (BOOL)removeAttributeWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (BOOL)clearAttributes SWIFT_WARN_UNUSED_RESULT;
@end

@interface LocalhostSplitClient (SWIFT_EXTENSION(Split))
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsByFlagSet:(NSString * _Nonnull)flagSet attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsByFlagSets:(NSArray<NSString *> * _Nonnull)flagSets attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigByFlagSet:(NSString * _Nonnull)flagSet attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigByFlagSets:(NSArray<NSString *> * _Nonnull)flagSets attributes:(NSDictionary<NSString *, id> * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsByFlagSet:(NSString * _Nonnull)flagSet attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getTreatmentsByFlagSets:(NSArray<NSString *> * _Nonnull)flagSets attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigByFlagSet:(NSString * _Nonnull)flagSet attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, SplitResult *> * _Nonnull)getTreatmentsWithConfigByFlagSets:(NSArray<NSString *> * _Nonnull)flagSets attributes:(NSDictionary<NSString *, id> * _Nullable)attributes evaluationOptions:(EvaluationOptions * _Nullable)evaluationOptions SWIFT_WARN_UNUSED_RESULT;
@end

/// SplitFactory implementation for Localhost mode
/// This mode is intended to use during development.
/// Check LocalhostSplitClient class for more information
/// seealso:
///
/// <a href="https://docs.split.io/docs/ios-sdk-overview#section-localhost">Split iOS SDK</a>
SWIFT_CLASS("_TtC5Split21LocalhostSplitFactory")
@interface LocalhostSplitFactory : NSObject <SplitFactory>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) enum UserConsent userConsent;
@property (nonatomic, readonly, strong) id <SplitClient> _Nonnull client;
@property (nonatomic, readonly, strong) id <SplitManager> _Nonnull manager;
@property (nonatomic, readonly, copy) NSString * _Nonnull version;
- (id <SplitClient> _Nonnull)clientWithKey:(Key * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (id <SplitClient> _Nonnull)clientWithMatchingKey:(NSString * _Nonnull)matchingKey SWIFT_WARN_UNUSED_RESULT;
- (id <SplitClient> _Nonnull)clientWithMatchingKey:(NSString * _Nonnull)matchingKey bucketingKey:(NSString * _Nullable)bucketingKey SWIFT_WARN_UNUSED_RESULT;
- (void)setUserConsentWithEnabled:(BOOL)enabled;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP5Split24SplitLocalhostDataSource_")
@protocol SplitLocalhostDataSource
- (BOOL)updateLocalhostWithYaml:(NSString * _Nonnull)yaml SWIFT_WARN_UNUSED_RESULT;
- (BOOL)updateLocalhostWithSplits:(NSString * _Nonnull)splits SWIFT_WARN_UNUSED_RESULT;
@end

@interface LocalhostSplitFactory (SWIFT_EXTENSION(Split)) <SplitLocalhostDataSource>
- (BOOL)updateLocalhostWithYaml:(NSString * _Nonnull)yaml SWIFT_WARN_UNUSED_RESULT;
- (BOOL)updateLocalhostWithSplits:(NSString * _Nonnull)splits SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC5Split7Matcher")
@interface Matcher : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface Matcher (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

typedef SWIFT_ENUM(NSInteger, MatcherCombiner, closed) {
  MatcherCombinerAnd = 0,
};

SWIFT_CLASS("_TtC5Split12MatcherGroup")
@interface MatcherGroup : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface MatcherGroup (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

SWIFT_CLASS("_TtC5Split20MatchesStringMatcher")
@interface MatchesStringMatcher : BaseMatcher
@end

SWIFT_CLASS_NAMED("MySegmentEntity")
@interface MySegmentEntity : NSManagedObject
@property (nonatomic, copy) NSString * _Nullable segmentList;
@property (nonatomic) int64_t updatedAt;
@property (nonatomic, copy) NSString * _Nullable userKey;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5Split16PartOfSetMatcher")
@interface PartOfSetMatcher : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split9Partition")
@interface Partition : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface Partition (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

SWIFT_CLASS("_TtC5Split12Prerequisite")
@interface Prerequisite : NSObject
@property (nonatomic, copy) NSString * _Nonnull flagName;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull treatments;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC5Split20PrerequisitesMatcher")
@interface PrerequisitesMatcher : BaseMatcher
@end

@class RolloutCacheConfigurationBuilder;
/// Configuration class for rollout cache. Internal use only.
SWIFT_CLASS("_TtC5Split25RolloutCacheConfiguration")
@interface RolloutCacheConfiguration : NSObject
/// Provides a builder for RolloutCacheConfiguration.
+ (RolloutCacheConfigurationBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("Builder")
@interface RolloutCacheConfigurationBuilder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (RolloutCacheConfiguration * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
/// Set the expiration time for the rollout definitions cache, in days. Default is 10 days.
/// \param expirationDays The expiration time in days.
///
///
/// returns:
/// This builder.
- (RolloutCacheConfigurationBuilder * _Nonnull)setExpirationDays:(NSInteger)expirationDays;
/// Set if the rollout definitions cache should be cleared on initialization. Default is false.
/// \param clearOnInit If the cache should be cleared on initialization.
///
///
/// returns:
/// This builder.
- (RolloutCacheConfigurationBuilder * _Nonnull)setClearOnInit:(BOOL)clearOnInit;
@end

SWIFT_CLASS("_TtC5Split16RuleBasedSegment")
@interface RuleBasedSegment : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5Split22RuleBasedSegmentChange")
@interface RuleBasedSegmentChange : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface RuleBasedSegmentChange (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

SWIFT_CLASS_NAMED("RuleBasedSegmentEntity")
@interface RuleBasedSegmentEntity : NSManagedObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull body;
@property (nonatomic) int64_t updatedAt;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, SegmentType, closed) {
  SegmentTypeStandard = 0,
  SegmentTypeRuleBased = 1,
  SegmentTypeLarge = 2,
  SegmentTypeUnknown = 3,
};

@class ServiceEndpointsBuilder;
SWIFT_CLASS("_TtC5Split16ServiceEndpoints")
@interface ServiceEndpoints : NSObject
+ (ServiceEndpointsBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("Builder")
@interface ServiceEndpointsBuilder : NSObject
/// The rest endpoint that sdk will hit for latest features and segments.
/// @param Endpoint MUST NOT be null
/// @return this builder
- (nonnull instancetype)setSdkEndpoint:(NSString * _Nonnull)sdkEndpoint SWIFT_WARN_UNUSED_RESULT;
/// The rest endpoint that sdk will hit to send events and impressions
/// @param eventsEndpoint: Base URL for events and impressions
/// @return this builder
- (nonnull instancetype)setEventsEndpoint:(NSString * _Nonnull)eventsEndpoint SWIFT_WARN_UNUSED_RESULT;
/// The rest endpoint that sdk will hit to get an SSE authentication token
/// to subscribe to SSE channels and receive update events
/// @param authServiceEndpoint: Base URL for Split API. Should include /api/vx.
/// @return this builder
- (nonnull instancetype)setAuthServiceEndpoint:(NSString * _Nonnull)authServiceEndpoint SWIFT_WARN_UNUSED_RESULT;
/// The rest endpoint that sdk will hit to subscribe to SSE channels
/// and receive update events
/// @param streamingServiceEndpoint: Base URL for streaming service
/// @return this builder
- (nonnull instancetype)setStreamingServiceEndpoint:(NSString * _Nonnull)streamingServiceEndpoint SWIFT_WARN_UNUSED_RESULT;
/// The rest endpoint that sdk will hit to send telemetry data
/// @param telemetryServiceEndpoint: Base URL for telemetry
/// @return this builder
- (nonnull instancetype)setTelemetryServiceEndpoint:(NSString * _Nonnull)telemetryServiceEndpoint SWIFT_WARN_UNUSED_RESULT;
- (ServiceEndpoints * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP5Split9SplitBase_")
@protocol SplitBase
@end

enum SplitEncryptionLevel : NSInteger;
SWIFT_CLASS("_TtC5Split19SplitBgSynchronizer")
@interface SplitBgSynchronizer : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SplitBgSynchronizer * _Nonnull shared;)
+ (SplitBgSynchronizer * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)registerWithDbKey:(NSString * _Nonnull)dbKey prefix:(NSString * _Nullable)prefix userKey:(NSString * _Nonnull)userKey encryptionLevel:(enum SplitEncryptionLevel)encryptionLevel;
- (void)unregisterWithDbKey:(NSString * _Nonnull)dbKey userKey:(NSString * _Nonnull)userKey;
- (void)unregisterAll;
- (void)scheduleWithServiceEndpoints:(ServiceEndpoints * _Nullable)serviceEndpoints SWIFT_AVAILABILITY(tvos_app_extension,unavailable) SWIFT_AVAILABILITY(ios_app_extension,unavailable);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5Split11SplitChange")
@interface SplitChange : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface SplitChange (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@interface SplitChange (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

@class SyncConfig;
@protocol SplitHttpsAuthenticator;
SWIFT_CLASS("_TtC5Split17SplitClientConfig")
@interface SplitClientConfig : NSObject
/// How many milliseconds to wait before triggering a timeout event when the SDK is being initialized.
/// Default: -1 (means no timeout)
@property (nonatomic) NSInteger sdkReadyTimeOut;
/// The SDK will poll Split servers for changes to feature flags at this rate (in seconds). Default 3600 (1 hour)
@property (nonatomic) NSInteger featuresRefreshRate;
/// The treatment log captures which customer saw what treatment (“on”, “off”, etc) at what time.
/// This log is periodically flushed back to Split servers.
/// This configuration controls how quickly does the cache expire after a write (in seconds).
/// Default: 1800 seconds (30 minutes)
@property (nonatomic) NSInteger impressionRefreshRate;
/// Maximum number of impressions to send in one block to the server.
/// Default 100
@property (nonatomic) int64_t impressionsChunkSize;
/// The SDK will poll Split servers for changes to segments at this rate (in seconds).
/// Default: 1800 seconds (30 minutes)
@property (nonatomic) NSInteger segmentsRefreshRate;
/// Default queue size for impressions. Default: 30K
@property (nonatomic) NSInteger impressionsQueueSize;
/// Timeout for HTTP calls in seconds. Default 30 seconds
@property (nonatomic) NSInteger connectionTimeout;
/// The traffic type associated with the client key.
/// If it’s present, it’s binded to the client instance, exactly as the key.
/// If not, we will expect the traffic type on each .track() call. This is an optional value.
@property (nonatomic, copy) NSString * _Nullable trafficType;
/// How much will we wait for the first events flush. Default: 10s.
@property (nonatomic) NSInteger eventsFirstPushWindow;
/// The schedule time for events flush after the first one. Default:  1800 seconds (30 minutes)
@property (nonatomic) NSInteger eventsPushRate;
/// The max size of the events queue. If the queue is full, we should flush. Default: 10000
@property (nonatomic) int64_t eventsQueueSize;
/// The amount of events to send in a POST request. Default: 2000
@property (nonatomic) NSInteger eventsPerPush;
/// The schedule time for metrics flush after the first one. Default:  1800 seconds (30 minutes)
@property (nonatomic) NSInteger metricsPushRate;
/// Client API key for company. Get it from Split admin dashboard.
@property (nonatomic, copy) NSString * _Nonnull apiKey;
@property (nonatomic, strong) ServiceEndpoints * _Nonnull serviceEndpoints;
/// Fallback Treatments at the SDK or flag level.
/// <h3>Usage Example:</h3>
/// \code
/// let fallbackTreatmentConfiguration = FallbackTreatmentConfiguration.builder()
///    .global(FallbackTreatment("off", config: "{\"config_value\":true}"))
///    .byFlag([
///       "my_flag": "false"
///    ])
///    .byFlag([
///      "my_flag_2": FallbackTreatment("false", "{\"message\": \"not found\"}")
///    ])
///    .build()
///  let config = SplitClientConfig.builder()
///    .fallbackTreatments(fallbackTreatmentConfiguration)
///    .build()
///
/// \endcode
@property (nonatomic, strong) FallbackTreatmentsConfig * _Nonnull fallbackTreatments;
/// Enables debug messages in console.
/// This method is deprecated in favor of logLevel.
@property (nonatomic) BOOL isDebugModeEnabled SWIFT_DEPRECATED_MSG("Use logLevel instead");
/// / Enables verbose messages in console.
/// This method is deprecated in favor of logLevel.
@property (nonatomic) BOOL isVerboseModeEnabled SWIFT_DEPRECATED_MSG("Use logLevel instead");
- (void)setWithLogLevel:(NSString * _Nonnull)logLevel;
/// Enables / Disables cache data encryption (Default: False)
@property (nonatomic) BOOL encryptionEnabled;
/// The logic to handle an impression log generated during a getTreatment call
/// <ul>
///   <li>
///     Parameters
///   </li>
///   <li>
///     A closure of type SplitImpressionListener, that means (SplitImpression) -> Void
///   </li>
/// </ul>
@property (nonatomic, copy) void (^ _Nullable impressionListener)(Impression * _Nonnull);
/// Data folder to store localhost feature flags file
/// <ul>
///   <li>
///     Default: localhost
///   </li>
/// </ul>
@property (nonatomic, copy) NSString * _Nonnull localhostDataFolder;
/// Localhost feature flags file name
@property (nonatomic, copy) NSString * _Nonnull splitFile;
/// Enable labels for impressions
@property (nonatomic) BOOL isLabelsEnabled;
/// Allows  to pass a list of filters for the feature flags that will be downloaded
/// Use the SyncConfig builder and Feature flag Filter class to build correct filters
@property (nonatomic, strong) SyncConfig * _Nonnull sync;
/// Whether we should attempt to use streaming or not. If the variable is false,
/// the SDK will start in polling mode and stay that way.
/// Default: true
@property (nonatomic) BOOL streamingEnabled;
/// Setup the impressions mode.
/// @param mode Values:<br>
/// DEBUG: All impressions are sent and
/// OPTIMIZED: Will send unique impressions in a timeframe in order to reduce how
/// many times impressions are posted.
/// NONE: Only capture unique keys evaluated for a particular feature flag instead of full blown impressions.
/// @return: This builder
/// @default: OPTIMIZED
@property (nonatomic, copy) NSString * _Nonnull impressionsMode;
/// Default: 1
@property (nonatomic) NSInteger pushRetryBackoffBase;
/// The SDK will load changes from feature flags files base on this feature. Default = -1 (Deactivated)
@property (nonatomic) NSInteger offlineRefreshRate;
/// When set to true app sync is done while app is in background.
/// Otherwise synchronization only occurs while app
/// is in foreground
@property (nonatomic) BOOL synchronizeInBackground;
/// Allows to perform a custom authentication on HTTPS requests.
/// This component must implement SplitHttpsAuthenticator protocol.
/// The function <em>authenticate:session:challenge:completionHandler</em> will be executed when the
/// [urlSession(_:didReceive:completionHandler:)]
/// (https://developer.apple.com/documentation/foundation/urlsessiondelegate/1409308-urlsession) is called.
@property (nonatomic, strong) id <SplitHttpsAuthenticator> _Nullable httpsAuthenticator;
/// The schedule time for telemetry flush after the first one.
/// Default: 3600 seconds (1 hour)
@property (nonatomic) NSInteger telemetryRefreshRate;
/// Make it mutable to allow testing (Default: false)
/// Enables persistent storage for common attributes  given by the user during the SDK
/// lifecycle to use them in every evaluation.
/// If this flags is set to false, attributes will be stored in memory only and their values
/// will be lost in SDK detroy.
@property (nonatomic) BOOL persistentAttributesEnabled;
/// Sync all retrieved data only once on init (Default: false)
/// No streaming neither polling service is enabled.
/// To get last definitions, the SDK have to be recreated
@property (nonatomic) BOOL syncEnabled;
/// Prefix applied to the cache database name (Default: nil)
/// This is useful when using two factories with the same SDK Key to avoid having issues with the shared data
@property (nonatomic, copy) NSString * _Nullable prefix;
/// The <code>CertificatePinningConfig</code> class is used to configure certificate pinning for a given set of hosts.
/// It holds an array of credentials, each of which represents a pin for a specific host,
/// either in the form of a certificate name or a base64-encoded key hash.
/// This configuration ensures that only trusted certificates are used for secure communication.
/// <h3>Usage Example:</h3>
/// \code
/// // Create a new builder instance
/// let builder = CertificatePinningConfig.builder()
///
/// // Add certificate pin for a host
/// builder.addPin(host: "example.com", certificateName: "example_cert")
///
/// // Add key hash pin for a host
/// builder.addPin(host: "example.com", keyHash: "sha256/aGVsbG8gd29ybGQ=")
///
/// // Build the CertificatePinningConfig
/// let config = try builder.build()
///
/// \endcodeThis example demonstrates how to add certificate and key hash pins for a host and build the configuration.
/// note:
/// The certificate files must be in DER format and included in the app bundle.
@property (nonatomic, strong) CertificatePinningConfig * _Nullable certificatePinningConfig;
/// Configuration for rollout definitions cache. Internal use only.
@property (nonatomic, strong) RolloutCacheConfiguration * _Nullable rolloutCacheConfiguration;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5Split8SplitDTO")
@interface SplitDTO : NSObject <SplitBase>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface SplitDTO (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

typedef SWIFT_ENUM(NSInteger, SplitEncryptionLevel, open) {
  SplitEncryptionLevelAes128Cbc = 0,
  SplitEncryptionLevelNone = 1,
};

SWIFT_CLASS_NAMED("SplitEntity")
@interface SplitEntity : NSManagedObject
@property (nonatomic, copy) NSString * _Nonnull body;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) int64_t updatedAt;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, SplitError, closed) {
  SplitErrorTimeout = 0,
  SplitErrorMatcherNoFound = 1,
};
static NSString * _Nonnull const SplitErrorDomain = @"Split.SplitError";

typedef SWIFT_ENUM(NSInteger, SplitEvent, open) {
  SplitEventSdkReady = 0,
  SplitEventSdkReadyTimedOut = 1,
  SplitEventSdkReadyFromCache = 2,
  SplitEventSdkUpdated = 3,
};

SWIFT_CLASS("_TtC5Split11SplitFilter")
@interface SplitFilter : NSObject
+ (SplitFilter * _Nonnull)byName:(NSArray<NSString *> * _Nonnull)values SWIFT_WARN_UNUSED_RESULT;
+ (SplitFilter * _Nonnull)byPrefix:(NSArray<NSString *> * _Nonnull)values SWIFT_WARN_UNUSED_RESULT;
+ (SplitFilter * _Nonnull)bySet:(NSArray<NSString *> * _Nonnull)values SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP5Split23SplitHttpsAuthenticator_")
@protocol SplitHttpsAuthenticator
- (void)authenticateSession:(NSURLSession * _Nonnull)session challenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
@end

SWIFT_CLASS("_TtC5Split11SplitResult")
@interface SplitResult : NSObject
@property (nonatomic, copy) NSString * _Nonnull treatment;
@property (nonatomic, copy) NSString * _Nullable config;
- (nonnull instancetype)initWithTreatment:(NSString * _Nonnull)treatment config:(NSString * _Nullable)config OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC5Split9SplitView")
@interface SplitView : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable trafficType;
@property (nonatomic, copy) NSString * _Nullable defaultTreatment;
@property (nonatomic, readonly) BOOL isKilled;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable treatments;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable sets;
@property (nonatomic, readonly, strong) NSNumber * _Nullable changeNum;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable configs;
@property (nonatomic, copy) NSArray<Prerequisite *> * _Nullable prerequisites;
@property (nonatomic) BOOL impressionsDisabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SplitView (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

SWIFT_CLASS("_TtC5Split16StartWithMatcher")
@interface StartWithMatcher : BaseMatcher
@end

typedef SWIFT_ENUM(NSInteger, Status, closed) {
  StatusActive = 0,
  StatusArchived = 1,
};

@class SyncConfigBuilder;
SWIFT_CLASS("_TtC5Split10SyncConfig")
@interface SyncConfig : NSObject
+ (SyncConfigBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("Builder")
@interface SyncConfigBuilder : NSObject
- (SyncConfig * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (SyncConfigBuilder * _Nonnull)addSplitFilter:(SplitFilter * _Nonnull)filter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5Split20TargetingRulesChange")
@interface TargetingRulesChange : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface TargetingRulesChange (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

SWIFT_CLASS("_TtC5Split11TrafficType")
@interface TrafficType : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC5Split9Treatment")
@interface Treatment : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface Treatment (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

SWIFT_CLASS("_TtC5Split23UnaryNumericMatcherData")
@interface UnaryNumericMatcherData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface UnaryNumericMatcherData (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

SWIFT_CLASS_NAMED("UniqueKeyEntity")
@interface UniqueKeyEntity : NSManagedObject
@property (nonatomic, copy) NSString * _Nonnull storageId;
@property (nonatomic, copy) NSString * _Nonnull userKey;
@property (nonatomic, copy) NSString * _Nonnull featureList;
@property (nonatomic) int64_t createdAt;
@property (nonatomic) int16_t sendAttemptCount;
@property (nonatomic) int32_t status;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, UserConsent, open) {
  UserConsentUnknown = 1,
  UserConsentGranted = 2,
  UserConsentDeclined = 3,
};

SWIFT_CLASS("_TtC5Split9Whitelist")
@interface Whitelist : BaseMatcher
@end

SWIFT_CLASS("_TtC5Split20WhitelistMatcherData")
@interface WhitelistMatcherData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface WhitelistMatcherData (SWIFT_EXTENSION(Split))
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
