#!/bin/zsh
# Checks tag name and create determines if it
# corresponds to a RC or STABLE release
REF=$1
STABLE_PATTERN='[0-9]+\.[0-9]+\.[0-9]+$'
RC_PATTERN='[0-9]+\.[0-9]+\.[0-9]+-(rc[0-9]+|SNAPSHOT)$'

[[ $REF =~ $STABLE_PATTERN ]]

if [ ! -z ${MATCH} ]
then
      echo 1
      exit
fi

[[ $REF =~ $RC_PATTERN ]]

if [ ! -z ${MATCH} ]
then
      echo 0
fi