#!/bin/zsh
clear
CUR_DIR=$(pwd)
SCHEMA_NAME=Split
BUILD_FOLDER=split_build
XCF_FOLDER=xcframework

echo "-----------------------------------"
echo "This scrip must be run from the folder containing Split.xcodeproj"
echo "It is intented to be used as a starter point to build a custom xcframework Split SDK\n"
echo "Example: ./scripts/generate_xcframework"
echo "-----------------------------------"
echo "\n"

rm -rf "${CUR_DIR}/${BUILD_FOLDER}"
rm -rf "${CUR_DIR}/${XCF_FOLDER}"

mkdir "${CUR_DIR}/${BUILD_FOLDER}"
mkdir "${CUR_DIR}/${XCF_FOLDER}"

echo "Archiving ${FRAMEWORK_NAME}"
xcodebuild build -scheme ${SCHEMA_NAME} -destination="iOS"  -derivedDataPath "${CUR_DIR}/${BUILD_FOLDER}" -sdk iphoneos -configuration release SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES
#Creating XCFramework
echo "Creating XCFramework from ${BUILD_FOLDER} "
xcodebuild -create-xcframework -framework "${CUR_DIR}/${BUILD_FOLDER}/Build/Products/Release-iphoneos/${SCHEMA_NAME}.framework" -output "${CUR_DIR}/${XCF_FOLDER}/Split.xcframework"

echo "Removing build folder"
rm -rf "${CUR_DIR}/${BUILD_FOLDER}"

echo "-----------------------------------"
echo "Split XCFramework is located in ${XCF_FOLDER}"
echo "-----------------------------------\n"