import Logging

/// Auto-generated by Kwift to verify dependency wiring at compile time.
private enum _KwiftDependencies {
    static func link() {
        // Ensure Logging module is linked
        _ = Logger.shared
    }
}