name: Build TvOS

on:
  pull_request:
    branches:
      - "**"

# Cancel in-progress runs when a new workflow with the same group is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/base_build.yaml
    with:
      destination: 'generic/platform=tvOS'
      scheme: Split
