name: Build WatchOS

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    uses: ./.github/workflows/base_build.yaml
    with:
      destination: 'generic/platform=watchOS'
      scheme: WatchOS
