name: Build TvOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: [macos-latest]

    steps:
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.1.0

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build tvOS
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          action: build
          build-settings: ONLY_ACTIVE_ARCH=NO TEST_AFTER_BUILD=NO
          configuration: Debug
          derived-data-path: "${{github.workspace}}/SplitApp"
          destination: 'generic/platform=tvOS'
          project: Split.xcodeproj
          scheme: Split
          use-xcpretty: true