name: Build TvOS

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    uses: ./.github/workflows/base_build.yaml
    with:
      destination: 'generic/platform=tvOS'
      scheme: Split
