name: Build TvOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - development
      - "*_baseline"

jobs:
  build:
    uses: ./.github/workflows/base_build.yaml
    with:
      destination: 'generic/platform=tvOS'
      scheme: Split
