name: SwiftFormat Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  format-check:
    name: SwiftFormat Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SwiftFormat
        run: |
          git clone https://github.com/nicklockwood/SwiftFormat
          cd SwiftFormat
          swift build -c release
          sudo cp .build/release/swiftformat /usr/local/bin/
        
      - name: Check if SwiftFormat has been run
        run: |
          swiftformat --lint --config .swiftformat Split
          if [ $? -ne 0 ]; then
            echo "::error::SwiftFormat check failed. Please run SwiftFormat locally before pushing."
            exit 1
          fi
