name: SwiftLint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: SwiftLint (Serious Violations Only)
        uses: norio-nomura/action-swiftlint@v3.2.1
        with:
          args: --strict
          reporter: github-actions-logging
          fail_on_error: true
