name: Build and Test iOS

on:
  pull_request:
    branches:
        - master
        - development
        - "*_baseline"

# Cancel in-progress runs when a new workflow with the same group is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        plan: [
            TestUnits/SplitiOSIntegration,
            TestUnits/SplitiOSIntegration_1,
            TestUnits/SplitiOSStreaming,
            TestUnits/SplitiOSStreaming_1,
            TestUnits/SplitiOSStreaming_2,
            TestUnits/SplitiOSUnit,
            TestUnits/SplitiOSUnit_1,
            TestUnits/SplitiOSUnit_2,
            TestUnits/SplitiOSUnit_3,
            TestUnits/SplitiOSUnit_4,
            TestUnits/SplitiOSUnit_5,
            TestUnits/SemVer,
            TestUnits/SplitPushManagerUT,
            TestUnits/SplitStreamingUT
        ]
      fail-fast: false
    uses: ./.github/workflows/base_ut.yaml
    with:
      test-plan: ${{ matrix.plan }}
      destination: 'platform=iOS Simulator,name=iPhone 16,OS=latest'
