name: Build and Test iOS

on:
  pull_request:
    branches:
        - master
        - development
        - "*_baseline"

# Cancel in-progress runs when a new workflow with the same group is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        plan: [
          TestPlans/SplitiOSIntegration,
          TestPlans/SplitiOSIntegration_1,
          TestPlans/SplitiOSStreaming,
          TestPlans/SplitiOSStreaming_1,
          TestPlans/SplitiOSStreaming_2,
          TestPlans/SplitiOSUnit,
          TestPlans/SplitiOSUnit_1,
          TestPlans/SplitiOSUnit_2,
          TestPlans/SplitiOSUnit_3,
          TestPlans/SplitiOSUnit_4,
          TestPlans/SplitiOSUnit_5,
          TestPlans/SemVer,
          TestPlans/SplitPushManagerUT,
          TestPlans/SplitStreamingUT,
          TestPlans/SplitFlakyTests
        ]
        scheme: [SplitTestsSwift5, SplitTestsSwift6]
      fail-fast: false
    uses: ./.github/workflows/base_ut.yaml
    with:
      test-plan: ${{ matrix.plan }}
      destination: 'platform=iOS Simulator,OS=18.5,name=iPhone 16'
      scheme: ${{ matrix.scheme }}

  modules-test:
    strategy:
      matrix:
        scheme: [ModulesTestsSwift5, ModulesTestsSwift6]
      fail-fast: false
    uses: ./.github/workflows/base_modules_ut.yaml
    with:
      destination: 'platform=iOS Simulator,OS=18.5,name=iPhone 16'
      scheme: ${{ matrix.scheme }}
